INSERT INTO T_CATEGORIA
(
    ID_CATEGORIA,
    NM_CATEGORIA
)
SELECT
    SQ_T_CATEGORIA.NEXTVAL,
    PRODUCT_CATEGORY_NAME
FROM
(
    SELECT DISTINCT PRODUCT_CATEGORY_NAME
    FROM STG_PRODUCTS
    WHERE PRODUCT_CATEGORY_NAME IS NOT NULL
);

INSERT INTO T_SUBCATEGORIA
(
    ID_SUBCATEGORIA,
    NM_SUBCATEGORIA,
    ID_CATEGORIA
)
SELECT
    SQ_T_SUBCATEGORIA.NEXTVAL,
    P.PRODUCT_CATEGORY_NAME,
    C.ID_CATEGORIA
FROM
(
    SELECT DISTINCT PRODUCT_CATEGORY_NAME
    FROM STG_PRODUCTS
    WHERE PRODUCT_CATEGORY_NAME IS NOT NULL
) P
JOIN T_CATEGORIA C
    ON P.PRODUCT_CATEGORY_NAME = C.NM_CATEGORIA;
    

INSERT INTO T_PRODUTO 
(      
    ID_PRODUTO,
    NM_PRODUTO,
    PRECO_BASE_PRODUTO,
    ID_SUBCATEGORIA
)
SELECT
    SQ_T_PRODUTO.NEXTVAL,
    PRODUCT_ID,
    0,
    S.ID_SUBCATEGORIA
FROM STG_PRODUCTS P
JOIN T_SUBCATEGORIA S
    ON P.PRODUCT_CATEGORY_NAME = S.NM_SUBCATEGORIA;

INSERT INTO T_CLIENTE
(
    ID_CLIENTE,
    NM_CLIENTE,
    SEGMENTO_CLIENTE,
    EMAIL_CLIENTE,
    CIDADE_CLIENTE,
    ESTADO_CLIENTE,
    PAIS_CLIENTE,
    DT_CADASTRO
)
SELECT
    SQ_T_CLIENTE.NEXTVAL,
    CUSTOMER_ID,
    'E-COMMERCE',
    CUSTOMER_ID || '@cliente.com',
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    'BRASIL',
    SYSDATE
FROM STG_CUSTOMERS;

INSERT INTO T_PEDIDO
(
    ID_PEDIDO,
    DT_PEDIDO,
    DT_ENVIO,
    ST_PEDIDO,
    PRIORIDADE_PEDIDO,
    VALOR_TOTAL_PEDIDO,
    DESCONTO_TOTAL_PEDIDO,
    ID_CLIENTE
)
SELECT
    SQ_T_PEDIDO.NEXTVAL,
    O.ORDER_PURCHASE_TIMESTAMP,
    NVL(O.ORDER_DELIVERED_CARRIER_DATE, O.ORDER_PURCHASE_TIMESTAMP),
    O.ORDER_STATUS,
    'NORMAL',
    0,
    0,
    C.ID_CLIENTE
FROM STG_ORDERS O
JOIN T_CLIENTE C
    ON O.CUSTOMER_ID = C.NM_CLIENTE;
    
INSERT INTO T_ITEM_PEDIDO
(
    ID_ITEM_PEDIDO,
    QNTD_ITEM_PEDIDO,
    PRECO_UNITARIO_ITEM_PEDIDO,
    DESCONTO_ITEM_PEDIDO,
    LUCRO_ITEM_PEDIDO,
    VALOR_TOTAL_ITEM_PEDIDO,
    ID_PEDIDO,
    ID_PRODUTO
)
SELECT
    SQ_T_ITEM_PEDIDO.NEXTVAL,
    1,
    OI.PRICE,
    0,
    0,
    OI.PRICE,
    P.ID_PEDIDO,
    PR.ID_PRODUTO
FROM STG_ORDER_ITEMS OI

JOIN STG_ORDERS SO
    ON OI.ORDER_ID = SO.ORDER_ID

JOIN T_CLIENTE C
    ON SO.CUSTOMER_ID = C.NM_CLIENTE

JOIN T_PEDIDO P
    ON C.ID_CLIENTE = P.ID_CLIENTE

JOIN T_PRODUTO PR
    ON OI.PRODUCT_ID = PR.NM_PRODUTO;
    

SELECT COUNT(*) FROM T_CLIENTE;
SELECT COUNT(*) FROM T_CATEGORIA;
SELECT COUNT(*) FROM T_SUBCATEGORIA;
SELECT COUNT(*) FROM T_PRODUTO;
SELECT COUNT(*) FROM T_PEDIDO;
SELECT COUNT(*) FROM T_ITEM_PEDIDO;