SELECT 
    C.NM_CATEGORIA,
    SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) AS RECEITA_TOTAL,
    ROUND(
        SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) /
        SUM(SUM(IP.VALOR_TOTAL_ITEM_PEDIDO)) OVER () * 100,
        2
    ) AS PERCENTUAL_RECEITA
FROM T_ITEM_PEDIDO IP
JOIN T_PRODUTO P
    ON IP.ID_PRODUTO = P.ID_PRODUTO
JOIN T_SUBCATEGORIA S
    ON P.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
JOIN T_CATEGORIA C
    ON S.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY C.NM_CATEGORIA
ORDER BY RECEITA_TOTAL DESC;

-------------------------------------------
SELECT *
FROM (
    SELECT 
        P.NM_PRODUTO,
        SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) AS RECEITA_TOTAL
    FROM T_ITEM_PEDIDO IP
    JOIN T_PRODUTO P
        ON IP.ID_PRODUTO = P.ID_PRODUTO
    GROUP BY P.NM_PRODUTO
    ORDER BY RECEITA_TOTAL DESC
)
WHERE ROWNUM <= 10;

-------------------------------------------
SELECT 
    C.ESTADO_CLIENTE,
    COUNT(P.ID_PEDIDO) AS TOTAL_PEDIDOS,
    SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) AS RECEITA_TOTAL
FROM T_PEDIDO P
JOIN T_CLIENTE C
    ON P.ID_CLIENTE = C.ID_CLIENTE
JOIN T_ITEM_PEDIDO IP
    ON P.ID_PEDIDO = IP.ID_PEDIDO
GROUP BY C.ESTADO_CLIENTE
ORDER BY RECEITA_TOTAL DESC;

-------------------------------------------
SELECT 
    ROUND(AVG(VALOR_PEDIDO),2) AS TICKET_MEDIO
FROM (
    SELECT 
        ID_PEDIDO,
        SUM(VALOR_TOTAL_ITEM_PEDIDO) AS VALOR_PEDIDO
    FROM T_ITEM_PEDIDO
    GROUP BY ID_PEDIDO
);

-------------------------------------------
SELECT *
FROM (
    SELECT 
        C.ID_CLIENTE,
        COUNT(P.ID_PEDIDO) AS TOTAL_PEDIDOS,
        SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) AS TOTAL_GASTO
    FROM T_CLIENTE C
    JOIN T_PEDIDO P
        ON C.ID_CLIENTE = P.ID_CLIENTE
    JOIN T_ITEM_PEDIDO IP
        ON P.ID_PEDIDO = IP.ID_PEDIDO
    GROUP BY C.ID_CLIENTE
    ORDER BY TOTAL_GASTO DESC
)
WHERE ROWNUM <= 10;

-------------------------------------------
SELECT 
    TO_CHAR(P.DT_PEDIDO,'YYYY-MM') AS MES,
    SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) AS RECEITA
FROM T_PEDIDO P
JOIN T_ITEM_PEDIDO IP
    ON P.ID_PEDIDO = IP.ID_PEDIDO
GROUP BY TO_CHAR(P.DT_PEDIDO,'YYYY-MM')
ORDER BY MES;