SELECT COUNT(*) FROM STG_CUSTOMERS;
SELECT COUNT(*) FROM STG_ORDERS;
SELECT COUNT(*) FROM STG_ORDER_ITEMS;
SELECT COUNT(*) FROM STG_PRODUCTS;
SELECT COUNT(*) FROM STG_CATEGORY_TRANSLATION;


SELECT * FROM STG_CUSTOMERS FETCH FIRST 10 ROWS ONLY;

SELECT * FROM STG_PRODUCTS FETCH FIRST 10 ROWS ONLY;



