SELECT COUNT(*) FROM STG_CUSTOMERS;
SELECT COUNT(*) FROM STG_ORDERS;
SELECT COUNT(*) FROM STG_ORDER_ITEMS;
SELECT COUNT(*) FROM STG_PRODUCTS;
SELECT COUNT(*) FROM STG_CATEGORY_TRANSLATION;


SELECT * FROM STG_CUSTOMERS FETCH FIRST 10 ROWS ONLY;

SELECT * FROM STG_PRODUCTS FETCH FIRST 10 ROWS ONLY;


SELECT 
    C.NM_CATEGORIA,
    SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) AS RECEITA_TOTAL
FROM T_ITEM_PEDIDO IP
JOIN T_PRODUTO P
    ON IP.ID_PRODUTO = P.ID_PRODUTO
JOIN T_SUBCATEGORIA S
    ON P.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
JOIN T_CATEGORIA C
    ON S.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY C.NM_CATEGORIA
ORDER BY RECEITA_TOTAL DESC;


SELECT 
    C.NM_CATEGORIA,
    SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) AS RECEITA_TOTAL,
    ROUND(
        SUM(IP.VALOR_TOTAL_ITEM_PEDIDO) /
        SUM(SUM(IP.VALOR_TOTAL_ITEM_PEDIDO)) OVER () * 100,
        2
    ) AS PERCENTUAL_RECEITA
FROM T_ITEM_PEDIDO IP
JOIN T_PRODUTO P
    ON IP.ID_PRODUTO = P.ID_PRODUTO
JOIN T_SUBCATEGORIA S
    ON P.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
JOIN T_CATEGORIA C
    ON S.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY C.NM_CATEGORIA
ORDER BY RECEITA_TOTAL DESC;